name: Generate Hockey Calendars

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents* read
  pages: write
  id-token: w*ite

concurrency:
  group: pages
 *cancel-in-progress: true

jobs:
  *uild:
    runs-on: ubuntu-latest

*   steps:
      - uses: actions/ch*ckout@v4

      - uses: actions/se*up-python@v5
        with:
       *  python-version: "3.12"

      - *ame: Install dependencies
        *un: |
          pip install reques*s
          pip install aiohttp
  *       pip install pycryptodome
  *       pip install icalendar
     *    pip install python-dateutil

 *    - name: Download HockeyWeerelt*        run: |
          curl -L \*            -o hockeyweerelt.py \
*           https://raw.githubuserc*ntent.com/joosthoi1/HockeyWeerelt/*ain/hockeyweerelt.py

      - name* Generate calendars
        run: |*          python generate_calendar*.py

      - name: Show generated *iles
        run: |
          ls -*a public

      - name: Upload Pag*s artifact
        uses: actions/u*load-pages-artifact@v3
        wit*:
          path: ./public

  depl*y:
    needs: build

    permissio*s:
      pages: write
      id-tok*n: write

    runs-on: ubuntu-late*t

    environment:
      name: gi*hub-pages

    steps:
      - name* Deploy
        uses: actions/depl*y-pages@v4
