name: Inspect HockeyWeerelt

on:
  workflow_dispatch:

jobs:
  inspect:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: |
          pip install requests
          pip install aiohttp
          pip install pycryptodome
          pip install icalendar
          pip install python-dateutil

      - run: |
          curl -L \
            -o hockeyweerelt.py \
            https://raw.githubusercontent.com/joosthoi1/HockeyWeerelt/main/hockeyweerelt.py

      - run: |
          grep -A 200 "class Api" hockeyweerelt.py

      - name: Run test
        run: |
          python generate_calendars.py
    
      - name: Install calendar packages
        run: |
          pip install icalendar
          pip install python-dateutil

      - name: Generate calendar
        run: |
          python generate_calendars.py
